config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'errors/not_found'
  get 'errors/unprocessable'
  get 'errors/internal_server_error'
  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'
  namespace :admin do
    resources :groups, except: %i[index new edit destroy]
    resources :categories, except: %i[index new edit destroy]
    resources :users, except: %i[index new edit destroy]
    resources :regulations, except: %i[index new edit destroy]
    resources :notifications, except: %i[index new edit destroy]
    resources :documents, except: %i[index new edit destroy]
    resources :carousels, except: %i[index new edit destroy]
    resources :news, except: %i[index new edit destroy]
  end

  # ADMIN
  get 'admin', to: 'admin/administrators#index'
  get 'tim-kiem-quan-tri', to: 'admin/administrators#search'
  #===============================PHÒNG BAN=================================================
  get 'admin/tat-ca-phong-ban', to: 'admin/groups#index', as: 'tat-ca-phong-ban'
  get 'admin/them-moi-phong-ban', to: 'admin/groups#new', as: 'them-moi-phong-ban'
  get 'admin/cap-nhat-phong-ban/:id', to: 'admin/groups#edit', as: 'cap-nhat-phong-ban'
  delete 'admin/xoa-phong-ban/:id', to: 'admin/groups#destroy', as: 'xoa-phong-ban'
  get 'admin/chi-tiet-phong-ban/:id', to: 'admin/groups#show', as: 'chi-tiet-phong-ban'
  #================================DANH MỤC=================================================
  get 'admin/tat-ca-danh-muc', to: 'admin/categories#index', as: 'tat-ca-danh-muc'
  get 'admin/them-moi-danh-muc', to: 'admin/categories#new', as: 'them-moi-danh-muc'
  get 'admin/cap-nhat-danh-muc/:id', to: 'admin/categories#edit', as: 'cap-nhat-danh-muc'
  delete 'admin/xoa-danh-muc/:id', to: 'admin/categories#destroy', as: 'xoa-danh-muc'
  get 'admin/chi-tiet-danh-muc/:id', to: 'admin/categories#show', as: 'chi-tiet-danh-muc'
  #================================NHÂN VIÊN================================================
  get 'admin/nhan-vien', to: 'admin/users#index', as: 'nhan-vien'
  get 'admin/them-moi-nhan-vien', to: 'admin/users#new', as: 'them-moi-nhan-vien'
  get 'admin/cap-nhat-nhan-vien/:id', to: 'admin/users#edit', as: 'cap-nhat-nhan-vien'
  delete 'admin/xoa-nhan-vien/:id', to: 'admin/users#destroy', as: 'xoa-nhan-vien'
  #============================QUY ĐỊNH, QUY TRÌNH==========================================
  get 'admin/quy-dinh-quy-trinh', to: 'admin/regulations#index', as: 'quy-dinh-quy-trinh'
  get 'admin/them-moi-quy-dinh-quy-trinh', to: 'admin/regulations#new', as: 'them-moi-quy-dinh-quy-trinh'
  get 'admin/cap-nhat-quy-dinh-quy-trinh/:id', to: 'admin/regulations#edit', as: 'cap-nhat-quy-dinh-quy-trinh'
  delete 'admin/xoa-quy-dinh-quy-trinh/:id', to: 'admin/regulations#destroy', as: 'xoa-quy-dinh-quy-trinh'
  #=================================THÔNG BÁO===============================================
  get 'admin/thong-bao', to: 'admin/notifications#index', as: 'thong-bao'
  get 'admin/them-moi-thong-bao', to: 'admin/notifications#new', as: 'them-moi-thong-bao'
  get 'admin/cap-nhat-thong-bao/:id', to: 'admin/notifications#edit', as: 'cap-nhat-thong-bao'
  delete 'admin/xoa-thong-bao/:id', to: 'admin/notifications#destroy', as: 'xoa-thong-bao'
  #=================================VĂN BẢN, BIỂU MẪU=======================================
  get 'admin/van-ban-bieu-mau', to: 'admin/documents#index', as: 'van-ban-bieu-mau'
  get 'admin/them-moi-van-ban-bieu-mau', to: 'admin/documents#new', as: 'them-moi-van-ban-bieu-mau'
  get 'admin/cap-nhat-van-ban-bieu-mau/:id', to: 'admin/documents#edit', as: 'cap-nhat-van-ban-bieu-mau'
  delete 'admin/xoa-van-ban-bieu-mau/:id', to: 'admin/documents#destroy', as: 'xoa-van-ban-bieu-mau'
  # =====================================TIN TỨC============================================
  get 'admin/tat-ca-tin-tuc', to: 'admin/news#index', as: 'tat-ca-tin-tuc'
  get 'admin/them-moi-tin-tuc', to: 'admin/news#new', as: 'them-moi-tin-tuc'
  get 'admin/cap-nhat-tin-tuc/:id', to: 'admin/news#edit', as: 'cap-nhat-tin-tuc'
  delete 'admin/xoa-tin-tuc/:id', to: 'admin/news#destroy', as: 'xoa-tin-tuc'
  # =======================================BĂNG RÔN=========================================
  get 'admin/tat-ca-bang-ron', to: 'admin/carousels#index', as: 'tat-ca-bang-ron'
  get 'admin/them-moi-bang-ron', to: 'admin/carousels#new', as: 'them-moi-bang-ron'
  get 'admin/cap-nhat-bang-ron/:id', to: 'admin/carousels#edit', as: 'cap-nhat-bang-ron'
  delete 'admin/xoa-bang-ron/:id', to: 'admin/carousels#destroy', as: 'xoa-bang-ron'

  # HOMEPAGE
  root 'home#index'
  get 'tim-kiem', to: 'home#search'
  devise_for :admins,
             controller: {
                registrations: 'admin/registrations'
             },
             path: '',
             path_names: {
               sign_in: 'dang-nhap',
               sign_out: 'dang-xuat',
               sign_up: 'them-moi-quan-tri-vien',
               edit: 'cap-nhat-thong-tin'
             }
  get 'tat-ca-nhan-vien', to: 'users#index'
  get 'chi-tiet-nhan-vien/:id', to: 'users#show', as: 'chi-tiet-nhan-vien'
  get 'tat-ca-nhan-vien-phong-ban/:id', to: 'groups#show', as: 'tat-ca-nhan-vien-phong-ban'

  get 'tat-ca-quy-dinh', to: 'regulations#index'
  get 'chi-tiet-quy-dinh/:id', to: 'regulations#show', as: 'chi-tiet-quy-dinh'
  get 'tat-ca-quy-dinh-danh-muc/:id', to: 'regulations#category_regulations', as: 'tat-ca-quy-dinh-danh-muc'

  get 'tat-ca-thong-bao', to: 'notifications#index'
  get 'chi-tiet-thong-bao/:id', to: 'notifications#show', as: 'chi-tiet-thong-bao'

  get 'thong-tin-chung', to: 'news#index'
  get 'chi-tiet-tin-tuc/:id', to: 'news#show', as: 'chi-tiet-tin-tuc'

  get 'tat-ca-van-ban', to: 'documents#index'
  get 'tat-ca-van-ban-phong-ban/:id', to: 'documents#group_documents', as: 'tat-ca-van-ban-phong-ban'

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < ApplicationController
  include Searchable
  before_action :authenticate_admin!
  def index
    @groups         = Group.all.order(created_at: :desc).limit(10)
    @users          = User.all.includes([:group]).order(created_at: :desc).limit(10)
    @categories     = Category.all.order(created_at: :desc).limit(10)
    @regulations    = Regulation.all.order(created_at: :desc).limit(10)
    @notifications  = Notification.all.order(created_at: :desc).limit(10)
    @documents      = Document.all.order(created_at: :desc).limit(10)
    @news           = News.all.order(created_at: :desc).limit(10)
  end

  def search
    @array_of_result_objects = Searchable.filter(params["search"]) if params["search"]
  end
end

app/views/admin/administrators/_categories.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>TẤT CẢ DANH MỤC</h5>
      </div>
      <div class="ibox-content">
        <table class="table table-striped table-bordered table-hover dataTables-example">
          <thead>
          <tr>
            <th>Tên</th>
            <th>Thông tin</th>
            <th>Tác vụ</th>
          </tr>
          </thead>
          <tbody>
          <% @categories.each do |category| %>
            <tr class="gradeA">
              <td><%= category.name %></td>
              <td>Có <strong><%= category.regulations.size %></strong> quy định, quy trình</td>
              <td>
                <%= link_to cap_nhat_danh_muc_path(category), class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-pencil"></i> Cập nhật
                <% end %>
                <%= link_to xoa_danh_muc_path(category), method: :delete, data: { confirm: "Bạn có chắc chắc muốn xoá danh mục này?" }, class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-trash"></i> Xoá
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/administrators/_documents.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>VĂN BẢN, BIỂU MẪU GẦN ĐÂY</h5>
      </div>
      <div class="ibox-content">
        <table class="table table-striped table-bordered table-hover dataTables-example">
          <thead>
          <tr>
            <th>Tiêu đề</th>
            <th>Tệp</th>
            <th>Tác vụ</th>
          </tr>
          </thead>
          <tbody>
          <% @documents.each do |document| %>
            <tr class="gradeA">
              <td><%= document.title %></td>
              <td>
                <% if document.attachment.url.split("/").last.include?("pdf") %>
                  Tệp đính kèm: </strong><%= link_to "#{document.attachment.file.filename}", pdfjs.full_path(file: "#{document.attachment.url}") %>
                <% else %>
                  Tải về: <i class="fa fa-download" aria-hidden="true"></i>
                  <%= link_to document.attachment.file.filename, document.attachment.url %>
                <% end %>
              </td>
              <td>
                <%= link_to cap_nhat_van_ban_bieu_mau_path(document), class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-pencil"></i> Cập nhật
                <% end %>
                <%= link_to xoa_van_ban_bieu_mau_path(document), method: :delete, data: { confirm: "Bạn có chắc chắc muốn xoá văn bản, biểu mẫu này?" }, class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-trash"></i> Xoá
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/administrators/_employees.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>NHÂN VIÊN GẦN ĐÂY</h5>
      </div>
      <div class="ibox-content">
        <table class="table table-striped table-bordered table-hover dataTables-example">
          <thead>
          <tr>
            <th>Họ tên</th>
            <th>Email</th>
            <th>Địa chỉ</th>
            <th>Điện thoại</th>
            <th>Năm sinh</th>
            <th>Phòng ban</th>
            <th>Thông tin</th>
            <th>Tác vụ</th>
          </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
            <tr class="gradeA">
              <td><%= user.name&.full %></td>
              <td><%= user.email %></td>
              <td><%= user.address %></td>
              <td><%= user.cell_phone %></td>
              <td><%= user.birthday %></td>
              <td><%= user.group_name %></td>
              <td><%= user.bio.truncate(100) %></td>
              <td>
                <%= link_to cap_nhat_nhan_vien_path(user), class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-pencil"></i> Cập nhật
                <% end %>
                <%= link_to xoa_nhan_vien_path(user), method: :delete, data: { confirm: "Bạn có chắc chắc muốn xoá nhân viên này?" }, class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-trash"></i> Xoá
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/administrators/_groups.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>PHÒNG BAN GẦN ĐÂY</h5>
      </div>
      <div class="ibox-content">
        <table class="table table-striped table-bordered table-hover dataTables-example">
          <thead>
          <tr>
            <th>Tên</th>
            <th>Thông tin</th>
            <th>Tác vụ</th>
          </tr>
          </thead>
          <tbody>
          <% @groups.each do |group| %>
            <tr class="gradeA">
              <td><%= link_to group.name, chi_tiet_phong_ban_path(group) %></td>
              <td>
                <ul>
                  <li class="dropdown">
                    Phòng <strong><%= group.name %></strong> có <strong><%= group.users.size %></strong> nhân viên
                  </li>
                </ul>
              </td>
              <td>
                <%= link_to cap_nhat_phong_ban_path(group), class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-pencil"></i> Cập nhật
                <% end %>
                <%= link_to xoa_phong_ban_path(group), method: :delete, data: { confirm: "Bạn có chắc chắc muốn xoá phòng ban này?" }, class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-trash"></i> Xoá
                <% end %>
              </td>
            </tr>
          <% end %>
          </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/administrators/_news.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>TIN TỨC GẦN ĐÂY</h5>
      </div>
      <div class="ibox-content">
        <table class="table table-striped table-bordered table-hover dataTables-example">
          <thead>
          <tr>
            <th>Tiêu đề</th>
            <th>Nội dung</th>
            <th>Tác vụ</th>
          </tr>
          </thead>
          <tbody>
          <% @news.each do |news| %>
            <tr class="gradeA">
              <td><%= news.title%></td>
              <td><%= news.body.truncate(200).html_safe %></td>
              <td>
                <%= link_to cap_nhat_tin_tuc_path(news), class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-pencil"></i> Cập nhật
                <% end %>
                <%= link_to xoa_tin_tuc_path(news), method: :delete, data: { confirm: "Bạn có chắc chắc muốn xoá tin tức này?" }, class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-trash"></i> Xoá
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/administrators/_notifications.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>THÔNG BÁO GẦN ĐÂY</h5>
      </div>
      <div class="ibox-content">
        <table class="table table-striped table-bordered table-hover dataTables-example">
          <thead>
          <tr>
            <th>Tiêu đề</th>
            <th>Nội dung</th>
            <th>Trạng thái</th>
            <th>Ngày tạo</th>
            <th>Tác vụ</th>
          </tr>
          </thead>
          <tbody>
          <% @notifications.each do |notification| %>
            <tr class="gradeA">
              <td><%= notification.title %></td>
              <td><%= notification.body.truncate(200).html_safe %></td>
              <td class="project-status">
                <% if notification.notable? %>
                  <span class="label label-danger"><%= notification.status_i18n %></span>
                <% else %>
                  <span class="label label-default"><%= notification.status_i18n %></span>
                <% end %>
              </td>
              <td><%= notification.created_at.strftime("%d-%m-%Y") %></td>
              <td>
                <%= link_to cap_nhat_thong_bao_path(notification), class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-pencil"></i> Cập nhật
                <% end %>
                <%= link_to xoa_thong_bao_path(notification), method: :delete, data: { confirm: "Bạn có chắc chắc muốn xoá quy định này?" }, class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-trash"></i> Xoá
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/administrators/_regulations.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>QUY ĐỊNH GẦN ĐÂY</h5>
      </div>
      <div class="ibox-content">
        <table class="table table-striped table-bordered table-hover dataTables-example">
          <thead>
          <tr>
            <th>Tiêu đề</th>
            <th>Nội dung</th>
            <th>Trạng thái</th>
            <th>Ngày tạo</th>
            <th>Tác vụ</th>
          </tr>
          </thead>
          <tbody>
          <% @regulations.each do |regulation| %>
            <tr class="gradeA">
              <td><%= regulation.title %></td>
              <td><%= raw regulation.body.truncate(200).html_safe %></td>
              <td class="project-status">
                <% if regulation.notable? %>
                  <span class="label label-danger"><%= regulation.status_i18n %></span>
                <% else %>
                  <span class="label label-default"><%= regulation.status_i18n %></span>
                <% end %>
              </td>
              <td><%= regulation.created_at.strftime("%d-%m-%Y") %></td>
              <td>
                <%= link_to cap_nhat_quy_dinh_quy_trinh_path(regulation), class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-pencil"></i> Cập nhật
                <% end %>
                <%= link_to xoa_quy_dinh_quy_trinh_path(regulation), method: :delete, data: { confirm: "Bạn có chắc chắc muốn xoá quy định này?" }, class:"btn btn-white btn-sm" do %>
                  <i class="fa fa-trash"></i> Xoá
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/administrators/_result.html.erb
<% if object.is_a? User %>
  <h4><%= link_to object.name.full, cap_nhat_nhan_vien_path(object), class:"text-danger" %></h4>
<% elsif object.is_a? Regulation %>
  <h4><%= link_to object.title, cap_nhat_quy_dinh_quy_trinh_path(object), class:"text-danger" %></h4>
<% elsif object.is_a? Notification %>
  <h4><%= link_to object.title, cap_nhat_thong_bao_path(object), class:"text-danger" %></h4>
<% elsif object.is_a? Document %>
  <h4><%= link_to object.title, cap_nhat_van_ban_bieu_mau_path(object), class:"text-danger" %></h4>
<% elsif object.is_a? News %>
  <h4><%= link_to object.title, cap_nhat_tin_tuc_path(object), class:"text-danger" %></h4>
<% elsif object.is_a? Group %>
<h4><%= link_to object.name, cap_nhat_phong_ban_path(object), class: "text-danger" %></h4>
<% end %>

app/views/admin/administrators/index.html.erb
<% provide(:title, 'Admin - Trang chủ') %>
<%= render 'shared/admin/navigation' %>
<%= render 'shared/admin/flash_messages' %>
<div id="page-wrapper" class="gray-bg">
  <%= render 'shared/admin/top_navbar' %>
  <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
      <h2>Tổng quan dữ liệu</h2>
      <ol class="breadcrumb">
        <li>
          <%= link_to 'Trang chủ', admin_path %>
        </li>
        <li class="active">
          <strong>Tổng quan</strong>
        </li>
      </ol>
    </div>
  </div>
  <div class="wrapper wrapper-content animated fadeInRight">
    <%= render 'admin/administrators/groups' %>
    <%= render 'admin/administrators/employees' %>
    <%= render 'admin/administrators/categories' %>
    <%= render 'admin/administrators/regulations' %>
    <%= render 'admin/administrators/notifications' %>
    <%= render 'admin/administrators/documents' %>
    <%= render 'admin/administrators/news' %>
  </div>
</div>
<%= render 'shared/admin/footer' %>

app/views/admin/administrators/search.html.erb
<% provide(:title, 'Admin - Tìm kiếm') %>
<%= render 'shared/admin/navigation' %>
<%= render 'shared/admin/flash_messages' %>
<div id="page-wrapper" class="gray-bg">
  <%= render 'shared/admin/top_navbar' %>
  <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
      <h2>Tổng quan dữ liệu</h2>
      <ol class="breadcrumb">
        <li>
          <%= link_to 'Trang chủ', admin_path %>
        </li>
        <li class="active">
          <strong>Kết quả tìm kiếm</strong>
        </li>
      </ol>
    </div>
  </div>
  <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
      <div class="col-lg-12">
        <div class="ibox float-e-margins">
          <div class="ibox-content">
            <table class="table table-striped table-bordered table-hover dataTables-example">
              <thead>
              <tr>
                <th>
                  <h4>Có <%= @array_of_result_objects.flatten.count %> kết quả tìm kiếm cho từ khoá: <span class="text-danger"><%= params["search"] %></span></h4>
                </th>
              </tr>
              </thead>
              <tbody>
              <% @array_of_result_objects.flatten.each do |array_of_result_object| %>
                <tr class="gradeX">
                  <td><%= render 'admin/administrators/result', object: array_of_result_object %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/admin/footer' %>