config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'errors/not_found'
  get 'errors/unprocessable'
  get 'errors/internal_server_error'
  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'
  namespace :admin do
    resources :groups, except: %i[index new edit destroy]
    resources :categories, except: %i[index new edit destroy]
    resources :users, except: %i[index new edit destroy]
    resources :regulations, except: %i[index new edit destroy]
    resources :notifications, except: %i[index new edit destroy]
    resources :documents, except: %i[index new edit destroy]
    resources :carousels, except: %i[index new edit destroy]
    resources :news, except: %i[index new edit destroy]
  end

  # ADMIN
  get 'admin', to: 'admin/administrators#index'
  get 'tim-kiem-quan-tri', to: 'admin/administrators#search'
  #===============================PHÒNG BAN=================================================
  get 'admin/tat-ca-phong-ban', to: 'admin/groups#index', as: 'tat-ca-phong-ban'
  get 'admin/them-moi-phong-ban', to: 'admin/groups#new', as: 'them-moi-phong-ban'
  get 'admin/cap-nhat-phong-ban/:id', to: 'admin/groups#edit', as: 'cap-nhat-phong-ban'
  delete 'admin/xoa-phong-ban/:id', to: 'admin/groups#destroy', as: 'xoa-phong-ban'
  get 'admin/chi-tiet-phong-ban/:id', to: 'admin/groups#show', as: 'chi-tiet-phong-ban'
  #================================DANH MỤC=================================================
  get 'admin/tat-ca-danh-muc', to: 'admin/categories#index', as: 'tat-ca-danh-muc'
  get 'admin/them-moi-danh-muc', to: 'admin/categories#new', as: 'them-moi-danh-muc'
  get 'admin/cap-nhat-danh-muc/:id', to: 'admin/categories#edit', as: 'cap-nhat-danh-muc'
  delete 'admin/xoa-danh-muc/:id', to: 'admin/categories#destroy', as: 'xoa-danh-muc'
  get 'admin/chi-tiet-danh-muc/:id', to: 'admin/categories#show', as: 'chi-tiet-danh-muc'
  #================================NHÂN VIÊN================================================
  get 'admin/nhan-vien', to: 'admin/users#index', as: 'nhan-vien'
  get 'admin/them-moi-nhan-vien', to: 'admin/users#new', as: 'them-moi-nhan-vien'
  get 'admin/cap-nhat-nhan-vien/:id', to: 'admin/users#edit', as: 'cap-nhat-nhan-vien'
  delete 'admin/xoa-nhan-vien/:id', to: 'admin/users#destroy', as: 'xoa-nhan-vien'
  #============================QUY ĐỊNH, QUY TRÌNH==========================================
  get 'admin/quy-dinh-quy-trinh', to: 'admin/regulations#index', as: 'quy-dinh-quy-trinh'
  get 'admin/them-moi-quy-dinh-quy-trinh', to: 'admin/regulations#new', as: 'them-moi-quy-dinh-quy-trinh'
  get 'admin/cap-nhat-quy-dinh-quy-trinh/:id', to: 'admin/regulations#edit', as: 'cap-nhat-quy-dinh-quy-trinh'
  delete 'admin/xoa-quy-dinh-quy-trinh/:id', to: 'admin/regulations#destroy', as: 'xoa-quy-dinh-quy-trinh'
  #=================================THÔNG BÁO===============================================
  get 'admin/thong-bao', to: 'admin/notifications#index', as: 'thong-bao'
  get 'admin/them-moi-thong-bao', to: 'admin/notifications#new', as: 'them-moi-thong-bao'
  get 'admin/cap-nhat-thong-bao/:id', to: 'admin/notifications#edit', as: 'cap-nhat-thong-bao'
  delete 'admin/xoa-thong-bao/:id', to: 'admin/notifications#destroy', as: 'xoa-thong-bao'
  #=================================VĂN BẢN, BIỂU MẪU=======================================
  get 'admin/van-ban-bieu-mau', to: 'admin/documents#index', as: 'van-ban-bieu-mau'
  get 'admin/them-moi-van-ban-bieu-mau', to: 'admin/documents#new', as: 'them-moi-van-ban-bieu-mau'
  get 'admin/cap-nhat-van-ban-bieu-mau/:id', to: 'admin/documents#edit', as: 'cap-nhat-van-ban-bieu-mau'
  delete 'admin/xoa-van-ban-bieu-mau/:id', to: 'admin/documents#destroy', as: 'xoa-van-ban-bieu-mau'
  # =====================================TIN TỨC============================================
  get 'admin/tat-ca-tin-tuc', to: 'admin/news#index', as: 'tat-ca-tin-tuc'
  get 'admin/them-moi-tin-tuc', to: 'admin/news#new', as: 'them-moi-tin-tuc'
  get 'admin/cap-nhat-tin-tuc/:id', to: 'admin/news#edit', as: 'cap-nhat-tin-tuc'
  delete 'admin/xoa-tin-tuc/:id', to: 'admin/news#destroy', as: 'xoa-tin-tuc'
  # =======================================BĂNG RÔN=========================================
  get 'admin/tat-ca-bang-ron', to: 'admin/carousels#index', as: 'tat-ca-bang-ron'
  get 'admin/them-moi-bang-ron', to: 'admin/carousels#new', as: 'them-moi-bang-ron'
  get 'admin/cap-nhat-bang-ron/:id', to: 'admin/carousels#edit', as: 'cap-nhat-bang-ron'
  delete 'admin/xoa-bang-ron/:id', to: 'admin/carousels#destroy', as: 'xoa-bang-ron'

  # HOMEPAGE
  root 'home#index'
  get 'tim-kiem', to: 'home#search'
  devise_for :admins,
             controller: {
                registrations: 'admin/registrations'
             },
             path: '',
             path_names: {
               sign_in: 'dang-nhap',
               sign_out: 'dang-xuat',
               sign_up: 'them-moi-quan-tri-vien',
               edit: 'cap-nhat-thong-tin'
             }
  get 'tat-ca-nhan-vien', to: 'users#index'
  get 'chi-tiet-nhan-vien/:id', to: 'users#show', as: 'chi-tiet-nhan-vien'
  get 'tat-ca-nhan-vien-phong-ban/:id', to: 'groups#show', as: 'tat-ca-nhan-vien-phong-ban'

  get 'tat-ca-quy-dinh', to: 'regulations#index'
  get 'chi-tiet-quy-dinh/:id', to: 'regulations#show', as: 'chi-tiet-quy-dinh'
  get 'tat-ca-quy-dinh-danh-muc/:id', to: 'regulations#category_regulations', as: 'tat-ca-quy-dinh-danh-muc'

  get 'tat-ca-thong-bao', to: 'notifications#index'
  get 'chi-tiet-thong-bao/:id', to: 'notifications#show', as: 'chi-tiet-thong-bao'

  get 'thong-tin-chung', to: 'news#index'
  get 'chi-tiet-tin-tuc/:id', to: 'news#show', as: 'chi-tiet-tin-tuc'

  get 'tat-ca-van-ban', to: 'documents#index'
  get 'tat-ca-van-ban-phong-ban/:id', to: 'documents#group_documents', as: 'tat-ca-van-ban-phong-ban'

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Searchable
  def index; end

  def search
    @array_of_result_objects = Searchable.filter(params["search"]) if params["search"]
  end
end

app/views/home/_result.html.erb
<% if object.is_a? User %>
  <h4><%= link_to object.name.full, chi_tiet_nhan_vien_path(object), class:"text-danger" %></h4>
<% elsif object.is_a? Regulation %>
  <h4><%= link_to object.title, chi_tiet_quy_dinh_path(object), class:"text-danger" %></h4>
<% elsif object.is_a? Notification %>
  <h4><%= link_to object.title, chi_tiet_thong_bao_path(object), class:"text-danger" %></h4>
<% elsif object.is_a? Document %>
  <% if object.attachment.url.split("/").last.include?("pdf") %>
    <p>
      <strong>Tệp đính kèm: </strong><%= link_to "#{object.attachment.file.filename}", pdfjs.full_path(file: "#{object.attachment.url}") %>
    </p>
  <% else %>
    <p>
      Tải về: <i class="fa fa-download" aria-hidden="true"></i>
      <%= link_to object.attachment.file.filename, object.attachment.url %>
    </p>
  <% end %>
<% elsif object.is_a? News %>
  <h4><%= link_to object.title, chi_tiet_tin_tuc_path(object), class:"text-danger" %></h4>
<% end %>

app/views/home/index.html.erb
<%= render 'shared/pages/navigation' %>
<%= render 'shared/pages/carousel' %>
<section class="container services m-b-xl">
  <div class="row">
    <div class="col-sm-3">
      <h3 class="text-center"><strong>QUY ĐỊNH, QUY TRÌNH</strong></h3>
      <hr style="height:2px;border-width:0;color: #c22b32;background-color: #c22b32">
        <%= image_tag("thong-bao.jpg", alt: "Banner quy định, quy trình", class:"img-responsive") %>
      <% if five_notable_regulations %>
        <% five_notable_regulations.each do |regulation| %>
          <h4><strong><%= link_to regulation.title, chi_tiet_quy_dinh_path(regulation) %></strong></h4>
          <p><%= regulation.body.truncate(100).html_safe %></p>
        <% end %>
      <% end %>
      <hr>
      <p>
        <%= link_to tat_ca_quy_dinh_path, class:"navy-link" do %>
          Xem thêm <i class="fa fa-angle-double-right" aria-hidden="true"></i>
        <% end %>
      </p>
    </div>
    <div class="col-sm-3">
      <h3 class="text-center"><strong>THÔNG BÁO</strong></h3>
      <hr style="height:2px;border-width:0;color: #c22b32;background-color: #c22b32">
      <%= image_tag("notifications.png", alt: "Banner thông báo", class:"img-responsive") %>
      <% if five_notable_notifications %>
        <% five_notable_notifications.each do |notification| %>
          <h4><strong><%= link_to notification.title, chi_tiet_thong_bao_path(notification) %></strong></h4>
          <p><%= notification.body.truncate(100).html_safe %></p>
        <% end %>
      <% end %>
      <hr>
      <p>
        <%= link_to tat_ca_thong_bao_path, class:"navy-link" do %>
          Xem thêm <i class="fa fa-angle-double-right" aria-hidden="true"></i>
        <% end %>
      </p>
    </div>
    <div class="col-sm-3">
      <h3 class="text-center"><strong>BIỂU MẪU</strong></h3>
      <hr style="height:2px;border-width:0;color: #c22b32;background-color: #c22b32">
      <%= image_tag("document.png", alt: "Banner văn bản", class:"img-responsive") %>
      <% if five_documents %>
        <% five_documents.each do |document| %>
          <h4><strong><%= link_to document&.title, document.attachment.url %></strong></h4>
        <% end %>
      <% end %>
      <hr>
      <p>
        <%= link_to tat_ca_van_ban_path, class:"navy-link" do %>
          Xem thêm <i class="fa fa-angle-double-right" aria-hidden="true"></i>
        <% end %>
      </p>
    </div>
    <div class="col-sm-3">
      <h3 class="text-center"><strong>TIN NỔI BẬT</strong></h3>
      <hr style="height:2px;border-width:0;color: #c22b32;background-color: #c22b32">
      <%= image_tag("news.jpg", alt: "Banner tin tức", class:"img-responsive") %>
      <% if five_notable_news %>
        <% five_notable_news.each do |news| %>
          <h4><strong><%= link_to news.title, chi_tiet_tin_tuc_path(news) %></strong></h4>
          <p><%= news&.body.truncate(100).html_safe %></p>
        <% end %>
      <% end %>
      <hr>
      <p>
        <%= link_to thong_tin_chung_path, class:"navy-link" do %>
          Xem thêm <i class="fa fa-angle-double-right" aria-hidden="true"></i>
        <% end %>
      </p>
    </div>
  </div>
</section>
<%= render 'shared/pages/footer' %>

app/views/home/search.html.erb
<%= render 'shared/pages/navigation' %>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-content">
          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
            <tr>
              <th>
                <h4>Có <%= @array_of_result_objects.flatten.count %> kết quả tìm kiếm cho từ khoá: <span class="text-danger"><%= params["search"] %></span></h4>
              </th>
            </tr>
            </thead>
            <tbody>
            <% @array_of_result_objects.flatten.each do |array_of_result_object| %>
              <tr class="gradeX">
                <td><%= render 'admin/administrators/result', object: array_of_result_object %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/pages/footer' %>