config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'errors/not_found'
  get 'errors/unprocessable'
  get 'errors/internal_server_error'
  mount PdfjsViewer::Rails::Engine => '/pdfjs', as: 'pdfjs'
  namespace :admin do
    resources :groups, except: %i[index new edit destroy]
    resources :categories, except: %i[index new edit destroy]
    resources :users, except: %i[index new edit destroy]
    resources :regulations, except: %i[index new edit destroy]
    resources :notifications, except: %i[index new edit destroy]
    resources :documents, except: %i[index new edit destroy]
    resources :carousels, except: %i[index new edit destroy]
    resources :news, except: %i[index new edit destroy]
  end

  # ADMIN
  get 'admin', to: 'admin/administrators#index'
  get 'tim-kiem-quan-tri', to: 'admin/administrators#search'
  #===============================PHÒNG BAN=================================================
  get 'admin/tat-ca-phong-ban', to: 'admin/groups#index', as: 'tat-ca-phong-ban'
  get 'admin/them-moi-phong-ban', to: 'admin/groups#new', as: 'them-moi-phong-ban'
  get 'admin/cap-nhat-phong-ban/:id', to: 'admin/groups#edit', as: 'cap-nhat-phong-ban'
  delete 'admin/xoa-phong-ban/:id', to: 'admin/groups#destroy', as: 'xoa-phong-ban'
  get 'admin/chi-tiet-phong-ban/:id', to: 'admin/groups#show', as: 'chi-tiet-phong-ban'
  #================================DANH MỤC=================================================
  get 'admin/tat-ca-danh-muc', to: 'admin/categories#index', as: 'tat-ca-danh-muc'
  get 'admin/them-moi-danh-muc', to: 'admin/categories#new', as: 'them-moi-danh-muc'
  get 'admin/cap-nhat-danh-muc/:id', to: 'admin/categories#edit', as: 'cap-nhat-danh-muc'
  delete 'admin/xoa-danh-muc/:id', to: 'admin/categories#destroy', as: 'xoa-danh-muc'
  get 'admin/chi-tiet-danh-muc/:id', to: 'admin/categories#show', as: 'chi-tiet-danh-muc'
  #================================NHÂN VIÊN================================================
  get 'admin/nhan-vien', to: 'admin/users#index', as: 'nhan-vien'
  get 'admin/them-moi-nhan-vien', to: 'admin/users#new', as: 'them-moi-nhan-vien'
  get 'admin/cap-nhat-nhan-vien/:id', to: 'admin/users#edit', as: 'cap-nhat-nhan-vien'
  delete 'admin/xoa-nhan-vien/:id', to: 'admin/users#destroy', as: 'xoa-nhan-vien'
  #============================QUY ĐỊNH, QUY TRÌNH==========================================
  get 'admin/quy-dinh-quy-trinh', to: 'admin/regulations#index', as: 'quy-dinh-quy-trinh'
  get 'admin/them-moi-quy-dinh-quy-trinh', to: 'admin/regulations#new', as: 'them-moi-quy-dinh-quy-trinh'
  get 'admin/cap-nhat-quy-dinh-quy-trinh/:id', to: 'admin/regulations#edit', as: 'cap-nhat-quy-dinh-quy-trinh'
  delete 'admin/xoa-quy-dinh-quy-trinh/:id', to: 'admin/regulations#destroy', as: 'xoa-quy-dinh-quy-trinh'
  #=================================THÔNG BÁO===============================================
  get 'admin/thong-bao', to: 'admin/notifications#index', as: 'thong-bao'
  get 'admin/them-moi-thong-bao', to: 'admin/notifications#new', as: 'them-moi-thong-bao'
  get 'admin/cap-nhat-thong-bao/:id', to: 'admin/notifications#edit', as: 'cap-nhat-thong-bao'
  delete 'admin/xoa-thong-bao/:id', to: 'admin/notifications#destroy', as: 'xoa-thong-bao'
  #=================================VĂN BẢN, BIỂU MẪU=======================================
  get 'admin/van-ban-bieu-mau', to: 'admin/documents#index', as: 'van-ban-bieu-mau'
  get 'admin/them-moi-van-ban-bieu-mau', to: 'admin/documents#new', as: 'them-moi-van-ban-bieu-mau'
  get 'admin/cap-nhat-van-ban-bieu-mau/:id', to: 'admin/documents#edit', as: 'cap-nhat-van-ban-bieu-mau'
  delete 'admin/xoa-van-ban-bieu-mau/:id', to: 'admin/documents#destroy', as: 'xoa-van-ban-bieu-mau'
  # =====================================TIN TỨC============================================
  get 'admin/tat-ca-tin-tuc', to: 'admin/news#index', as: 'tat-ca-tin-tuc'
  get 'admin/them-moi-tin-tuc', to: 'admin/news#new', as: 'them-moi-tin-tuc'
  get 'admin/cap-nhat-tin-tuc/:id', to: 'admin/news#edit', as: 'cap-nhat-tin-tuc'
  delete 'admin/xoa-tin-tuc/:id', to: 'admin/news#destroy', as: 'xoa-tin-tuc'
  # =======================================BĂNG RÔN=========================================
  get 'admin/tat-ca-bang-ron', to: 'admin/carousels#index', as: 'tat-ca-bang-ron'
  get 'admin/them-moi-bang-ron', to: 'admin/carousels#new', as: 'them-moi-bang-ron'
  get 'admin/cap-nhat-bang-ron/:id', to: 'admin/carousels#edit', as: 'cap-nhat-bang-ron'
  delete 'admin/xoa-bang-ron/:id', to: 'admin/carousels#destroy', as: 'xoa-bang-ron'

  # HOMEPAGE
  root 'home#index'
  get 'tim-kiem', to: 'home#search'
  devise_for :admins,
             controller: {
                registrations: 'admin/registrations'
             },
             path: '',
             path_names: {
               sign_in: 'dang-nhap',
               sign_out: 'dang-xuat',
               sign_up: 'them-moi-quan-tri-vien',
               edit: 'cap-nhat-thong-tin'
             }
  get 'tat-ca-nhan-vien', to: 'users#index'
  get 'chi-tiet-nhan-vien/:id', to: 'users#show', as: 'chi-tiet-nhan-vien'
  get 'tat-ca-nhan-vien-phong-ban/:id', to: 'groups#show', as: 'tat-ca-nhan-vien-phong-ban'

  get 'tat-ca-quy-dinh', to: 'regulations#index'
  get 'chi-tiet-quy-dinh/:id', to: 'regulations#show', as: 'chi-tiet-quy-dinh'
  get 'tat-ca-quy-dinh-danh-muc/:id', to: 'regulations#category_regulations', as: 'tat-ca-quy-dinh-danh-muc'

  get 'tat-ca-thong-bao', to: 'notifications#index'
  get 'chi-tiet-thong-bao/:id', to: 'notifications#show', as: 'chi-tiet-thong-bao'

  get 'thong-tin-chung', to: 'news#index'
  get 'chi-tiet-tin-tuc/:id', to: 'news#show', as: 'chi-tiet-tin-tuc'

  get 'tat-ca-van-ban', to: 'documents#index'
  get 'tat-ca-van-ban-phong-ban/:id', to: 'documents#group_documents', as: 'tat-ca-van-ban-phong-ban'

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/regulation.rb
require 'babosa'
class Regulation < ApplicationRecord
  # Upload file for regulation
  mount_uploaders :attachments, AttachmentUploader
  serialize :attachments, JSON

  # URL Friendly
  extend FriendlyId
  friendly_id :title, use: :slugged
  def normalize_friendly_id(input)
    input.to_slug.normalize(transliterations: :vietnamese).to_s
  end

  # Validations
  # validates :title, presence: true, length: { in: 10..100 }
  # validates :status, presence: true

  # Associations
  belongs_to :category
  belongs_to :group

  # Delegate name for category, group
  delegate :name, to: :category, prefix: :category, allow_nil: true
  delegate :name, to: :group, prefix: :group, allow_nil: true

  enum status: { normal: 0, notable: 1 }

  scope :search_by_title, lambda { |query|
    where('lower(title) LIKE ?', "%#{query}%")
  }
end

app/controllers/admin/regulations_controller.rb
class Admin::RegulationsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_regulation, only: %i[show edit update destroy]

  def index
    @pagy, @regulations = pagy(Regulation.all.includes([:group, :category]).order(created_at: :desc))
  end

  def show; end

  def new
    @regulation = Regulation.new
  end

  def edit; end

  def create
    @regulation = Regulation.new(regulation_params)

    respond_to do |format|
      if @regulation.save
        format.html { redirect_to quy_dinh_quy_trinh_path, notice: 'Quy định, quy trình đã được tạo thành công.' }
      else
        # format.html { redirect_to quy_dinh_quy_trinh_path, alert: "#{@regulation.errors.full_messages.join('\n').html_safe}" }
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @regulation.update(regulation_params)
        format.html { redirect_to quy_dinh_quy_trinh_path, notice: 'Quy định, quy trình đã được cập nhật thành công.' }
      else
        # format.html { redirect_to cap_nhat_quy_dinh_quy_trinh_path(@regulation), alert: "#{@regulation.errors.full_messages.join('\n').html_safe}" }
        format.html { render :edit }
      end
    end
  end

  def destroy
    @regulation.destroy
    respond_to do |format|
      format.html { redirect_to quy_dinh_quy_trinh_path, notice: 'Quy định, quy trình đã được xoá thành công.' }
    end
  end

  private
  def set_regulation
    @regulation = Regulation.friendly.find(params[:id])
  end

  def regulation_params
    params.require(:regulation).permit(:title, :body, :status, :category_id, :group_id, attachments: [])
  end
end

app/controllers/regulations_controller.rb
class RegulationsController < ApplicationController
  before_action :set_page_regulation, only: %i[show]
  def index
    @page_regulations        = Regulation.all
    @pagy, @page_regulations = pagy(@page_regulations)
  end

  def show; end

  def category_regulations
    @page_category                = Category.friendly.find(params["id"])
    @pagy, @category_regulations  = pagy(Regulation.where(category_id: @page_category&.id))
  end

  private
  def set_page_regulation
    @page_regulation = Regulation.friendly.find(params["id"])
  end
end

app/helpers/regulation_helper.rb
module RegulationHelper
  def five_notable_regulations
    all_notable_regulations  = Regulation.notable.order(created_at: :desc)
    five_notable_regulations = all_notable_regulations.limit(5) if all_notable_regulations.any?
  end
end

app/views/regulations/_regulations.html.erb
<% objects.each do |object| %>
  <tr class="gradeX">
    <td><p><%= link_to object.title, chi_tiet_quy_dinh_path(object) %></p></td>
    <td>
      <%= object.body.truncate(200).html_safe %>
    </td>
    <td>
      <% object.attachments.each do |attachment| %>
        <% if attachment.url.split("/").last.include?("pdf") %>
          <strong>Tệp đính kèm: </strong><%= link_to "#{attachment.file.filename}", pdfjs.full_path(file: "#{attachment.url}") %>
        <% else %>
          <strong>Tải về:</strong> <i class="fa fa-download" aria-hidden="true"></i>
          <%= link_to attachment.file.filename, "#{attachment.url}" %>
        <% end %>
      <% end %>
    </td>
    <td class="center"><%= object.created_at.strftime("%d-%m-%Y") %></td>
  </tr>
<% end %>

app/views/regulations/category_regulations.html.erb
<% provide(:title, 'Quy định, quy trình') %>
<%= render 'shared/pages/navigation' %>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-content">

          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
            <tr>
              <th>Tiêu đề</th>
              <th>Nội dung</th>
              <th>Tệp</th>
              <th>Ngày tạo</th>
            </tr>
            </thead>
            <tbody>
            <%= render 'regulations/regulations', objects: @category_regulations %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/pages/pagy_navigation' %>
<%= render 'shared/pages/footer' %>

app/views/regulations/index.html.erb
<% provide(:title, 'Quy định, quy trình') %>
<%= render 'shared/pages/navigation' %>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-content">
          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
            <tr>
              <th>Tiêu đề</th>
              <th>Nội dung</th>
              <th>Tệp</th>
              <th>Ngày tạo</th>
            </tr>
            </thead>
            <tbody>
              <%= render 'regulations/regulations', objects: @page_regulations %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/pages/pagy_navigation' %>
<%= render 'shared/pages/footer' %>

app/views/regulations/show.html.erb
<% provide(:title, 'Chi tiết quy định, quy trình') %>
<%= render 'shared/pages/navigation' %>
<div class="wrapper wrapper-content  animated fadeInRight article">
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="ibox">
        <div class="ibox-content">
          <div class="pull-right">
            <button class="btn btn-primary btn-xs" type="button"><%= @page_regulation.group_name %></button>
            <button class="btn btn-info btn-xs" type="button"><%= @page_regulation.category_name %></button>
          </div>
          <div class="text-center article-title">
            <span class="text-muted"><i class="fa fa-clock-o"></i> <%= @page_regulation.created_at.strftime("%d-%m-%Y") %></span>
            <h3>
              <%= @page_regulation.title %>
            </h3>
          </div>
          <p>
            <%= @page_regulation.body.to_s.html_safe %>
          </p>
          <% @page_regulation.attachments.each do |attachment| %>
            <% if attachment.url.split("/").last.include?("pdf") %>
              <strong>Tệp đính kèm: </strong><%= link_to "#{attachment.file.filename}", pdfjs.full_path(file: "#{attachment.url}") %>
            <% else %>
              <strong>Tải về:</strong> <i class="fa fa-download" aria-hidden="true"></i>
              <%= link_to attachment.file.filename, "#{attachment.url}" %>
            <% end %>
          <% end %>
          <span class="pull-right">
              <%= link_to tat_ca_quy_dinh_danh_muc_path(@page_regulation.category_id), class: "btn btn-primary" do %>
                <i class="fa fa-angle-double-left" aria-hidden="true"></i> Quay lại
              <% end %>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/pages/footer' %>